### ISSUE TITLE
readdir hang if have more than 23 entries

### ISSUE THREAD

**Issue by jbui007** [libfuse/pyfuse3#5] opened 2018-10-16 22:42 UTC
Maybe I am using this wrong but when try to do ls on a directory that has more than 23 files readdir stuck in a endless loop.  
Below is the function for readdir - the off param does not start at 0 if you have more than 23 entries.  
it increment by one as you add more entries.  I cannot find where this being pass in - 
Can you help?
this same code work using the old llfuse module

```
    async def readdir(self, dirinode, off, token):
        log.debug('readdir %d starting at %d', dirinode, off)
        log.debug("readdir token: {}".format(token))
        dirnode = self.superblock[dirinode]
        assert dirnode.type == NodeType.Dir
        log.debug("readdir DIR node: {}, enum: {}".format(dirnode, enumerate(dirnode.children[off:])))

        for n, child in enumerate(dirnode.children[off:]):
            log.debug("CHILD: {}, n={}".format(child.name, n))
            pyfuse3.readdir_reply(token, child.name, await self.getattr(child.inode), n+1)

        log.debug("\n\n****readdir END LOOP, dirinode {} offset={}\n".format(dirinode, off))
```

**Comment by jbui007** [comment] 2018-10-16 22:48
Example output when not work - 
```

2018-10-16 16:46:39.639 MainThread: [__main__] getattr for inode 383:<pyfuse3.EntryAttributes object at 0x7f6457c2ebe8>
2018-10-16 16:46:39.639 MainThread: [__main__] readdir 383 starting at 1
2018-10-16 16:46:39.639 MainThread: [__main__] readdir token: <pyfuse3.ReaddirToken object at 0x7f64573aa120>
2018-10-16 16:46:39.639 MainThread: [__main__] readdir DIR node: (383 voltages NodeType.Dir 40755 0 1001)
	[(b'v_max_battery_collection' 359), (b'v_psoc_die_temperature' 360), (b'v_measure' 361), (b'v_all' 362), (b'v_battery_report_low_delay' 363), (b'v_therm1' 364), (b'v_sys_3v8' 365), (b'v_bat' 366), (b'v_voltage_activate' 367), (b'v_therm_1_temperature' 368), (b'v_battery_window_high' 369), (b'v_spare_4' 370), (b'v_battery_window_low' 371), (b'v_therm_2_resistance' 372), (b'v_nominal' 373), (b'v_high_threshold' 374), (b'v_scale' 375), (b'v_therm_batt' 376), (b'v_battery_present' 377), (b'v_connect_voltage' 378), (b'v_wall' 379), (b'v_battery_thermal_threshold' 380), (b'v_battery_thermal_threshold2' 381), (b'v_therm_1_resistance' 382)], enum: <enumerate object at 0x7f64573ae1f8>
2018-10-16 16:46:39.639 MainThread: [__main__] CHILD: b'v_psoc_die_temperature', n=0
2018-10-16 16:46:39.639 MainThread: [__main__] getattr for inode 360:<pyfuse3.EntryAttributes object at 0x7f6457c2b8c8>
2018-10-16 16:46:39.639 MainThread: [__main__] CHILD: b'v_measure', n=1
2018-10-16 16:46:39.639 MainThread: [__main__] getattr for inode 361:<pyfuse3.EntryAttributes object at 0x7f6457c2b990>
2018-10-16 16:46:39.639 MainThread: [__main__] CHILD: b'v_all', n=2
2018-10-16 16:46:39.639 MainThread: [__main__] getattr for inode 362:<pyfuse3.EntryAttributes object at 0x7f6457c2ba58>
2018-10-16 16:46:39.639 MainThread: [__main__] CHILD: b'v_battery_report_low_delay', n=3
2018-10-16 16:46:39.639 MainThread: [__main__] getattr for inode 363:<pyfuse3.EntryAttributes object at 0x7f6457c2bb20>
2018-10-16 16:46:39.639 MainThread: [__main__] CHILD: b'v_therm1', n=4
2018-10-16 16:46:39.639 MainThread: [__main__] getattr for inode 364:<pyfuse3.EntryAttributes object at 0x7f6457c2bbe8>
2018-10-16 16:46:39.639 MainThread: [__main__] CHILD: b'v_sys_3v8', n=5
2018-10-16 16:46:39.639 MainThread: [__main__] getattr for inode 365:<pyfuse3.EntryAttributes object at 0x7f6457c2bcb0>
2018-10-16 16:46:39.639 MainThread: [__main__] CHILD: b'v_bat', n=6
2018-10-16 16:46:39.639 MainThread: [__main__] getattr for inode 366:<pyfuse3.EntryAttributes object at 0x7f6457c2bd78>
2018-10-16 16:46:39.639 MainThread: [__main__] CHILD: b'v_voltage_activate', n=7
2018-10-16 16:46:39.639 MainThread: [__main__] getattr for inode 367:<pyfuse3.EntryAttributes object at 0x7f6457c2be40>
2018-10-16 16:46:39.639 MainThread: [__main__] CHILD: b'v_therm_1_temperature', n=8
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 368:<pyfuse3.EntryAttributes object at 0x7f6457c2bf08>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_battery_window_high', n=9
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 369:<pyfuse3.EntryAttributes object at 0x7f6457c2e030>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_spare_4', n=10
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 370:<pyfuse3.EntryAttributes object at 0x7f6457c2e0f8>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_battery_window_low', n=11
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 371:<pyfuse3.EntryAttributes object at 0x7f6457c2e1c0>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_therm_2_resistance', n=12
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 372:<pyfuse3.EntryAttributes object at 0x7f6457c2e288>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_nominal', n=13
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 373:<pyfuse3.EntryAttributes object at 0x7f6457c2e350>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_high_threshold', n=14
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 374:<pyfuse3.EntryAttributes object at 0x7f6457c2e418>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_scale', n=15
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 375:<pyfuse3.EntryAttributes object at 0x7f6457c2e4e0>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_therm_batt', n=16
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 376:<pyfuse3.EntryAttributes object at 0x7f6457c2e670>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_battery_present', n=17
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 377:<pyfuse3.EntryAttributes object at 0x7f6457c2e738>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_connect_voltage', n=18
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 378:<pyfuse3.EntryAttributes object at 0x7f6457c2e800>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_wall', n=19
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 379:<pyfuse3.EntryAttributes object at 0x7f6457c2e8c8>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_battery_thermal_threshold', n=20
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 380:<pyfuse3.EntryAttributes object at 0x7f6457c2e990>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_battery_thermal_threshold2', n=21
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 381:<pyfuse3.EntryAttributes object at 0x7f6457c2ea58>
2018-10-16 16:46:39.640 MainThread: [__main__] CHILD: b'v_therm_1_resistance', n=22
2018-10-16 16:46:39.640 MainThread: [__main__] getattr for inode 382:<pyfuse3.EntryAttributes object at 0x7f6457c2eb20>
2018-10-16 16:46:39.640 MainThread: [__main__] 

****readdir END LOOP, dirinode 383 offset=1

2018-10-16 16:46:39.641 MainThread: [__main__] getattr for inode 383:<pyfuse3.EntryAttributes object at 0x7f6457c2ebe8>
2018-10-16 16:46:39.641 MainThread: [__main__] readdir 383 starting at 23
2018-10-16 16:46:39.641 MainThread: [__main__] readdir token: <pyfuse3.ReaddirToken object at 0x7f64573aa120>
2018-10-16 16:46:39.641 MainThread: [__main__] readdir DIR node: (383 voltages NodeType.Dir 40755 0 1001)
	[(b'v_max_battery_collection' 359), (b'v_psoc_die_temperature' 360), (b'v_measure' 361), (b'v_all' 362), (b'v_battery_report_low_delay' 363), (b'v_therm1' 364), (b'v_sys_3v8' 365), (b'v_bat' 366), (b'v_voltage_activate' 367), (b'v_therm_1_temperature' 368), (b'v_battery_window_high' 369), (b'v_spare_4' 370), (b'v_battery_window_low' 371), (b'v_therm_2_resistance' 372), (b'v_nominal' 373), (b'v_high_threshold' 374), (b'v_scale' 375), (b'v_therm_batt' 376), (b'v_battery_present' 377), (b'v_connect_voltage' 378), (b'v_wall' 379), (b'v_battery_thermal_threshold' 380), (b'v_battery_thermal_threshold2' 381), (b'v_therm_1_resistance' 382)], enum: <enumerate object at 0x7f64573ae240>
2018-10-16 16:46:39.641 MainThread: [__main__] CHILD: b'v_therm_1_resistance', n=0
2018-10-16 16:46:39.641 MainThread: [__main__] getattr for inode 382:<pyfuse3.EntryAttributes object at 0x7f6457c2eb20>
2018-10-16 16:46:39.641 MainThread: [__main__] 

****readdir END LOOP, dirinode 383 offset=23

2018-10-16 16:46:39.641 MainThread: [__main__] getattr for inode 383:<pyfuse3.EntryAttributes object at 0x7f6457c2ebe8>
2018-10-16 16:46:39.641 MainThread: [__main__] readdir 383 starting at 1
2018-10-16 16:46:39.641 MainThread: [__main__] readdir token: <pyfuse3.ReaddirToken object at 0x7f64573aa120>
2018-10-16 16:46:39.641 MainThread: [__main__] readdir DIR node: (383 voltages NodeType.Dir 40755 0 1001)
	[(b'v_max_battery_collection' 359), (b'v_psoc_die_temperature' 360), (b'v_measure' 361), (b'v_all' 362), (b'v_battery_report_low_delay' 363), (b'v_therm1' 364), (b'v_sys_3v8' 365), (b'v_bat' 366), (b'v_voltage_activate' 367), (b'v_therm_1_temperature' 368), (b'v_battery_window_high' 369), (b'v_spare_4' 370), (b'v_battery_window_low' 371), (b'v_therm_2_resistance' 372), (b'v_nominal' 373), (b'v_high_threshold' 374), (b'v_scale' 375), (b'v_therm_batt' 376), (b'v_battery_present' 377), (b'v_connect_voltage' 378), (b'v_wall' 379), (b'v_battery_thermal_threshold' 380), (b'v_battery_thermal_threshold2' 381), (b'v_therm_1_resistance' 382)], enum: <enumerate object at 0x7f64573ae1b0>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_psoc_die_temperature', n=0
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 360:<pyfuse3.EntryAttributes object at 0x7f6457c2b8c8>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_measure', n=1
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 361:<pyfuse3.EntryAttributes object at 0x7f6457c2b990>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_all', n=2
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 362:<pyfuse3.EntryAttributes object at 0x7f6457c2ba58>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_battery_report_low_delay', n=3
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 363:<pyfuse3.EntryAttributes object at 0x7f6457c2bb20>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_therm1', n=4
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 364:<pyfuse3.EntryAttributes object at 0x7f6457c2bbe8>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_sys_3v8', n=5
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 365:<pyfuse3.EntryAttributes object at 0x7f6457c2bcb0>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_bat', n=6
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 366:<pyfuse3.EntryAttributes object at 0x7f6457c2bd78>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_voltage_activate', n=7
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 367:<pyfuse3.EntryAttributes object at 0x7f6457c2be40>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_therm_1_temperature', n=8
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 368:<pyfuse3.EntryAttributes object at 0x7f6457c2bf08>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_battery_window_high', n=9
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 369:<pyfuse3.EntryAttributes object at 0x7f6457c2e030>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_spare_4', n=10
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 370:<pyfuse3.EntryAttributes object at 0x7f6457c2e0f8>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_battery_window_low', n=11
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 371:<pyfuse3.EntryAttributes object at 0x7f6457c2e1c0>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_therm_2_resistance', n=12
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 372:<pyfuse3.EntryAttributes object at 0x7f6457c2e288>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_nominal', n=13
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 373:<pyfuse3.EntryAttributes object at 0x7f6457c2e350>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_high_threshold', n=14
2018-10-16 16:46:39.642 MainThread: [__main__] getattr for inode 374:<pyfuse3.EntryAttributes object at 0x7f6457c2e418>
2018-10-16 16:46:39.642 MainThread: [__main__] CHILD: b'v_scale', n=15
2018-10-16 16:46:39.643 MainThread: [__main__] getattr for inode 375:<pyfuse3.EntryAttributes object at 0x7f6457c2e4e0>
2018-10-16 16:46:39.643 MainThread: [__main__] CHILD: b'v_therm_batt', n=16
2018-10-16 16:46:39.643 MainThread: [__main__] getattr for inode 376:<pyfuse3.EntryAttributes object at 0x7f6457c2e670>
2018-10-16 16:46:39.643 MainThread: [__main__] CHILD: b'v_battery_present', n=17
2018-10-16 16:46:39.643 MainThread: [__main__] getattr for inode 377:<pyfuse3.EntryAttributes object at 0x7f6457c2e738>
2018-10-16 16:46:39.643 MainThread: [__main__] CHILD: b'v_connect_voltage', n=18
2018-10-16 16:46:39.643 MainThread: [__main__] getattr for inode 378:<pyfuse3.EntryAttributes object at 0x7f6457c2e800>
2018-10-16 16:46:39.643 MainThread: [__main__] CHILD: b'v_wall', n=19
2018-10-16 16:46:39.643 MainThread: [__main__] getattr for inode 379:<pyfuse3.EntryAttributes object at 0x7f6457c2e8c8>
2018-10-16 16:46:39.643 MainThread: [__main__] CHILD: b'v_battery_thermal_threshold', n=20
2018-10-16 16:46:39.643 MainThread: [__main__] getattr for inode 380:<pyfuse3.EntryAttributes object at 0x7f6457c2e990>
2018-10-16 16:46:39.643 MainThread: [__main__] CHILD: b'v_battery_thermal_threshold2', n=21
2018-10-16 16:46:39.643 MainThread: [__main__] getattr for inode 381:<pyfuse3.EntryAttributes object at 0x7f6457c2ea58>
2018-10-16 16:46:39.643 MainThread: [__main__] CHILD: b'v_therm_1_resistance', n=22
2018-10-16 16:46:39.643 MainThread: [__main__] getattr for inode 382:<pyfuse3.EntryAttributes object at 0x7f6457c2eb20>
2018-10-16 16:46:39.643 MainThread: [__main__] 

****readdir END LOOP, dirinode 383 offset=1

```

**Comment by jbui007** [comment] 2018-10-16 22:49
Working version output:
```
2018-10-16 16:48:20.385 MainThread: [__main__] opendir 382
2018-10-16 16:48:20.386 MainThread: [__main__] readdir 382 starting at 0
2018-10-16 16:48:20.386 MainThread: [__main__] readdir token: <pyfuse3.ReaddirToken object at 0x7f6913c59120>
2018-10-16 16:48:20.386 MainThread: [__main__] readdir DIR node: (382 voltages NodeType.Dir 40755 0 1001)
	[(b'v_max_battery_collection' 359), (b'v_psoc_die_temperature' 360), (b'v_measure' 361), (b'v_all' 362), (b'v_battery_report_low_delay' 363), (b'v_therm1' 364), (b'v_sys_3v8' 365), (b'v_bat' 366), (b'v_voltage_activate' 367), (b'v_therm_1_temperature' 368), (b'v_battery_window_high' 369), (b'v_spare_4' 370), (b'v_battery_window_low' 371), (b'v_therm_2_resistance' 372), (b'v_nominal' 373), (b'v_high_threshold' 374), (b'v_scale' 375), (b'v_therm_batt' 376), (b'v_battery_present' 377), (b'v_connect_voltage' 378), (b'v_wall' 379), (b'v_battery_thermal_threshold' 380), (b'v_therm_1_resistance' 381)], enum: <enumerate object at 0x7f6913c52ee8>
2018-10-16 16:48:20.387 MainThread: [__main__] CHILD: b'v_max_battery_collection', n=0
2018-10-16 16:48:20.387 MainThread: [__main__] getattr for inode 359:<pyfuse3.EntryAttributes object at 0x7f69144d6800>
2018-10-16 16:48:20.387 MainThread: [__main__] CHILD: b'v_psoc_die_temperature', n=1
2018-10-16 16:48:20.387 MainThread: [__main__] getattr for inode 360:<pyfuse3.EntryAttributes object at 0x7f69144d68c8>
2018-10-16 16:48:20.387 MainThread: [__main__] CHILD: b'v_measure', n=2
2018-10-16 16:48:20.387 MainThread: [__main__] getattr for inode 361:<pyfuse3.EntryAttributes object at 0x7f69144d6990>
2018-10-16 16:48:20.387 MainThread: [__main__] CHILD: b'v_all', n=3
2018-10-16 16:48:20.387 MainThread: [__main__] getattr for inode 362:<pyfuse3.EntryAttributes object at 0x7f69144d6a58>
2018-10-16 16:48:20.388 MainThread: [__main__] CHILD: b'v_battery_report_low_delay', n=4
2018-10-16 16:48:20.388 MainThread: [__main__] getattr for inode 363:<pyfuse3.EntryAttributes object at 0x7f69144d6b20>
2018-10-16 16:48:20.388 MainThread: [__main__] CHILD: b'v_therm1', n=5
2018-10-16 16:48:20.388 MainThread: [__main__] getattr for inode 364:<pyfuse3.EntryAttributes object at 0x7f69144d6be8>
2018-10-16 16:48:20.388 MainThread: [__main__] CHILD: b'v_sys_3v8', n=6
2018-10-16 16:48:20.388 MainThread: [__main__] getattr for inode 365:<pyfuse3.EntryAttributes object at 0x7f69144d6cb0>
2018-10-16 16:48:20.388 MainThread: [__main__] CHILD: b'v_bat', n=7
2018-10-16 16:48:20.388 MainThread: [__main__] getattr for inode 366:<pyfuse3.EntryAttributes object at 0x7f69144d6d78>
2018-10-16 16:48:20.388 MainThread: [__main__] CHILD: b'v_voltage_activate', n=8
2018-10-16 16:48:20.389 MainThread: [__main__] getattr for inode 367:<pyfuse3.EntryAttributes object at 0x7f69144d6e40>
2018-10-16 16:48:20.389 MainThread: [__main__] CHILD: b'v_therm_1_temperature', n=9
2018-10-16 16:48:20.389 MainThread: [__main__] getattr for inode 368:<pyfuse3.EntryAttributes object at 0x7f69144d6f08>
2018-10-16 16:48:20.389 MainThread: [__main__] CHILD: b'v_battery_window_high', n=10
2018-10-16 16:48:20.389 MainThread: [__main__] getattr for inode 369:<pyfuse3.EntryAttributes object at 0x7f69144dc030>
2018-10-16 16:48:20.389 MainThread: [__main__] CHILD: b'v_spare_4', n=11
2018-10-16 16:48:20.389 MainThread: [__main__] getattr for inode 370:<pyfuse3.EntryAttributes object at 0x7f69144dc0f8>
2018-10-16 16:48:20.389 MainThread: [__main__] CHILD: b'v_battery_window_low', n=12
2018-10-16 16:48:20.390 MainThread: [__main__] getattr for inode 371:<pyfuse3.EntryAttributes object at 0x7f69144dc1c0>
2018-10-16 16:48:20.390 MainThread: [__main__] CHILD: b'v_therm_2_resistance', n=13
2018-10-16 16:48:20.390 MainThread: [__main__] getattr for inode 372:<pyfuse3.EntryAttributes object at 0x7f69144dc288>
2018-10-16 16:48:20.390 MainThread: [__main__] CHILD: b'v_nominal', n=14
2018-10-16 16:48:20.390 MainThread: [__main__] getattr for inode 373:<pyfuse3.EntryAttributes object at 0x7f69144dc350>
2018-10-16 16:48:20.390 MainThread: [__main__] CHILD: b'v_high_threshold', n=15
2018-10-16 16:48:20.390 MainThread: [__main__] getattr for inode 374:<pyfuse3.EntryAttributes object at 0x7f69144dc418>
2018-10-16 16:48:20.390 MainThread: [__main__] CHILD: b'v_scale', n=16
2018-10-16 16:48:20.390 MainThread: [__main__] getattr for inode 375:<pyfuse3.EntryAttributes object at 0x7f69144dc4e0>
2018-10-16 16:48:20.391 MainThread: [__main__] CHILD: b'v_therm_batt', n=17
2018-10-16 16:48:20.391 MainThread: [__main__] getattr for inode 376:<pyfuse3.EntryAttributes object at 0x7f69144dc670>
2018-10-16 16:48:20.391 MainThread: [__main__] CHILD: b'v_battery_present', n=18
2018-10-16 16:48:20.391 MainThread: [__main__] getattr for inode 377:<pyfuse3.EntryAttributes object at 0x7f69144dc738>
2018-10-16 16:48:20.391 MainThread: [__main__] CHILD: b'v_connect_voltage', n=19
2018-10-16 16:48:20.391 MainThread: [__main__] getattr for inode 378:<pyfuse3.EntryAttributes object at 0x7f69144dc800>
2018-10-16 16:48:20.391 MainThread: [__main__] CHILD: b'v_wall', n=20
2018-10-16 16:48:20.391 MainThread: [__main__] getattr for inode 379:<pyfuse3.EntryAttributes object at 0x7f69144dc8c8>
2018-10-16 16:48:20.391 MainThread: [__main__] CHILD: b'v_battery_thermal_threshold', n=21
2018-10-16 16:48:20.391 MainThread: [__main__] getattr for inode 380:<pyfuse3.EntryAttributes object at 0x7f69144dc990>
2018-10-16 16:48:20.391 MainThread: [__main__] CHILD: b'v_therm_1_resistance', n=22
2018-10-16 16:48:20.391 MainThread: [__main__] getattr for inode 381:<pyfuse3.EntryAttributes object at 0x7f69144dca58>
2018-10-16 16:48:20.391 MainThread: [__main__] 

****readdir END LOOP, dirinode 382 offset=0

2018-10-16 16:48:20.391 MainThread: [__main__] getattr for inode 382:<pyfuse3.EntryAttributes object at 0x7f69144dcb20>
2018-10-16 16:48:20.391 MainThread: [__main__] readdir 382 starting at 23
2018-10-16 16:48:20.391 MainThread: [__main__] readdir token: <pyfuse3.ReaddirToken object at 0x7f6913c59120>
2018-10-16 16:48:20.391 MainThread: [__main__] readdir DIR node: (382 voltages NodeType.Dir 40755 0 1001)
	[(b'v_max_battery_collection' 359), (b'v_psoc_die_temperature' 360), (b'v_measure' 361), (b'v_all' 362), (b'v_battery_report_low_delay' 363), (b'v_therm1' 364), (b'v_sys_3v8' 365), (b'v_bat' 366), (b'v_voltage_activate' 367), (b'v_therm_1_temperature' 368), (b'v_battery_window_high' 369), (b'v_spare_4' 370), (b'v_battery_window_low' 371), (b'v_therm_2_resistance' 372), (b'v_nominal' 373), (b'v_high_threshold' 374), (b'v_scale' 375), (b'v_therm_batt' 376), (b'v_battery_present' 377), (b'v_connect_voltage' 378), (b'v_wall' 379), (b'v_battery_thermal_threshold' 380), (b'v_therm_1_resistance' 381)], enum: <enumerate object at 0x7f6913c52f78>
2018-10-16 16:48:20.391 MainThread: [__main__] 

****readdir END LOOP, dirinode 382 offset=23

```

**Comment by Nikratio** [comment] 2018-10-17 14:02
Thanks for the report! Could you clarify what file system you are using? Can you reproduce this problem with one of the examples?

If not, then the problem is probably with how you have implemented readdir(). The *off* that is passed in will be either zero or one of the values that you have passed to `readdir_reply` before (in the *next_id* argument).

**Comment by Nikratio** [comment] 2018-10-17 14:56
I mean the *fuse* filesystem that you are using here, that's definitely not ext4 :-). Example should be fixed now, so please give it another go.

**Comment by jbui007** [comment] 2018-10-17 15:15
Thanks, we emulate our FS for _sys_ and _dev_ so we can run some test without running on hardware.
The examples works, I am going to debug our side and see why it not working for us.

**Closed** 2018-10-17 15:16 UTC
Labels: needs-info
